### PR TITLE
Update panel.html

### PR DESCRIPTION
**Pull request by tech165**
Related to issue 52.

Replace paper-toggle-button to mwc-switch for configuration to work with HASS > 0.100 . Should work for pre 0.100 version but untested. Tested with 0.101 and working great. 

Thanks

### CODE REVIEW

**Comment by akasma74** [comment]
thanks, will test it and add to the next release.

**Comment by tech165** [comment]
Seem it is not working with 0.99 ... will have to find another solution

**Comment by akasma74** [comment]
I have to close this PR as [the fix](https://github.com/akasma74/Hass-Custom-Alarm/releases/tag/v1.10.3) is a bit more sofisticated than just migrating to mwc-switch (btw, it's better to use ha-switch).

**Comment by tech165** [comment]
Thanks for your work ! I’m new to polymer, that was a great way to fix it. Thanks again.

**Pull request closed without merging**
